-- Table schema for shipments with raw, parsed, and engineered fields
CREATE TABLE shipments (
    port_code TEXT,
    date DATE,
    iec TEXT,
    hs_code TEXT,
    goods_description TEXT,
    master_category TEXT,
    model_name TEXT,
    model_number TEXT,
    capacity TEXT,
    qty NUMERIC,
    unit_of_measure TEXT,
    price NUMERIC,
    price_uom TEXT,
    quantity NUMERIC,
    unit TEXT,
    unit_price_inr NUMERIC,
    total_value_inr NUMERIC,
    unit_price_usd NUMERIC,
    total_value_usd NUMERIC,
    duty_paid_inr NUMERIC,
    year INT,
    month INT,
    quarter INT,
    unit_standardized TEXT,
    grand_total_inr NUMERIC,
    category TEXT,
    sub_category TEXT,
    landed_cost_per_unit NUMERIC
);
